image: "python:2.7"

before_script:
  - python --version

stages:
  - Generate OMPL

csv2opml:
  stage: Generate OPML
  script:
  - python ./converters/csv2opml.py media-release-rss.csv media-release-rss.opml
